### ISSUE TITLE
service_provider fact not mocked correctly / consistently

### ISSUE THREAD

**Issue by zilchms** [voxpupuli/voxpupuli-test#124]
There seems to exist a problem where the service_provider fact is not correctly or consistently mocked.
The module itself seems to get the correct facts, the spec tests on the other hand seem to sometimes not get these facts (even though os_facts gets loaded correctly)
The problem itself seems to occur a bit random, but then consistently (retriggering the workflow does not lead to correct provisioning)

Eg. https://github.com/voxpupuli/puppet-kafka/actions/runs/7799015682/job/21269032637?pr=336#step:5:22

@bastelfreak could reproduce this accross multiple modules.
I am not sure whether this is a problem of this gem or a more general problem for rspec test implementation accross our modules.
This issue serves the purpose to track the issue.

**Comment by ekohl** [comment]
The problem is that rspec-puppet-facts uses strings for custom facts, not symbols. https://github.com/voxpupuli/rspec-puppet-facts/pull/157 will make it consistent but I've opened in the short term https://github.com/voxpupuli/puppet-kafka/pull/351 for that specific module.
