### ISSUE TITLE
question on rake check:trailing_whitespace: trailing whitespaces in markdown

### ISSUE THREAD

**Issue by rwaffen** [voxpupuli/voxpupuli-test#139]
In markdown it is allowed to have trailing whitespaces to indicate a line break, with our rake-check extention we say, this is not allowed. why are we doing this?

**Comment by bastelfreak** [comment]
I don't like linebreaks via whitespace because than you cannot differentiate between accidental whitespace and on-purpose-whitespace.

**Comment by rwaffen** [comment]
yep, i see this like you. trailing spaces as control characters are a bad decission :(

maybe we should say that we only acknowledge the [github markdown flavor](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)?

**Comment by bastelfreak** [comment]
ah yes that's a good idea.
